name: Release Notes to Confluence Publisher
author: Gershon Alvais
modified_by: Martin Žigrai
description: Confluence Release BOT. This action sends a CHANGELOG.md and creates a page in Confluence.
branding:
  icon: "book"
  color: "blue"

inputs:
  status:
    required: true
    type: string
  title:
    description: Title of the page. Release tag.
    required: true
    type: string
  pageId:    
    description: Parent page id. The release page will be created under this page.
    required: true
    type: string    
  ConfluenceBaseUrl:
    description: Confluence base url
    required: true
    type: string
  confluence_email:
    description: "Confluence Email"
    required: true
    type: string
  confluence_api_token:
    description: "Confluence API Token"
    required: true
    type: string
  appName:
    description: Name of the app. This will be used in the release notes.
    required: true
    type: string
  repoOwner:
    description: Owner of the repository. This will be used to fetch the release notes.
    required: true
    type: string
  repoName:
    description: Name of the repository. This will be used to fetch the release notes.
    required: true
    type: string
  changelogName:
    description: In a repository, there could be multiple changelog files. This parameter serves to identify which changelog to retrieve and sends it to the corresponding Confluence page.
    required: true
    type: string
  branchName:
    description: Name of the branch.
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get CHANGELOG
      id: get-changelog
      uses: actions/github-script@v7
      with:
        script: |
          const repoOwner = '${{ inputs.repoOwner }}'; 
          const repoName = '${{ inputs.repoName }}'; 
          const changelogName = '${{ inputs.changelogName }}';
          const branch = '${{ inputs.branchName }}';

          const { data: fileInfo } = await github.rest.repos.getContent({
            owner: repoOwner,
            repo: repoName,
            path: changelogName,
            ref: branch
          });

          const changelogContent = Buffer.from(fileInfo.content, 'base64').toString('utf-8');
          // console.log(changelogContent); // 

          core.setOutput("changelogContent", changelogContent);

          return { changelogContent };
          


    - name: Install pandoc
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Create or Update Release Notes Page in Confluence
      id: create_or_update_confluence_page
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.get-changelog.outputs.changelogContent }}
        REPO_URL: "https://github.com/${{ inputs.repoOwner }}/${{ inputs.repoName }}"


      run: |
        echo "Changelog content from previous step:"
        echo "${RELEASE_NOTES}"

        page_id="${{ inputs.pageId }}"

        # Get existing page content
        existing_page_response=$(curl --request GET \
          --url "${{ inputs.ConfluenceBaseUrl }}/rest/api/content/${page_id}?expand=body.storage,version" \
          --user "${{ inputs.confluence_email }}:${{ inputs.confluence_api_token }}" \
          --header 'Accept: application/json' \
          --silent)

        existing_content=$(echo "$existing_page_response" | jq -r '.body.storage.value // ""')
        existing_version=$(echo "$existing_page_response" | jq -r '.version.number')

        RELEASE_DATE=$(date +"%d-%m-%Y")
        ADDITIONAL_INFO="# INFORMATION ABOUT PRODUCT\n\n "
        ADDITIONAL_INFO+="**Release date:** ${RELEASE_DATE}\\\n "  
        ADDITIONAL_INFO+="**Link to repository:** [${REPO_URL}](${REPO_URL})\\\n\n " 

        # Combine additional info and changelog in Markdown
        COMBINED_CONTENT="${ADDITIONAL_INFO} ${RELEASE_NOTES}"


        # Convert Markdown to HTML
        COMBINED_CONTENT_HTML=$(echo "$COMBINED_CONTENT" | pandoc -f markdown -t html)

        # Increment version number
        new_version=$((existing_version + 1))

        # Create updated payload
        payload=$(jq -n \
            --arg value "$COMBINED_CONTENT_HTML" \
            --arg version "$new_version" \
            --arg title "${{ inputs.title }}" \
            '{
                "version": { "number": ($version | tonumber) },
                "title": $title,
                "type": "page",
                "body": {
                    "storage": {
                        "value": $value,
                        "representation": "storage"
                    }
                }
            }')

        # Update existing page with new content
        update_response=$(curl --request PUT \
          --url "${{ inputs.ConfluenceBaseUrl }}/rest/api/content/${page_id}" \
          --user "${{ inputs.confluence_email }}:${{ inputs.confluence_api_token }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "$payload")

        # Check for errors in the update response
        if [[ $(echo "$update_response" | jq -r '.statusCode // empty') ]]; then
          error_message=$(echo "$update_response" | jq -r '.message // "No error message"')
          echo "Error updating Confluence page: $error_message"
          exit 1
        fi